arb-dir: lib/l10n
template-arb-file: app_ja.arb
output-localization-file: l10n.dart
output-class: L10n
synthetic-package: false

translator:
  key_file: translator_key
  service: deepl
  targets:
    - en
    - ko
    - fr
    - zh