name: supabase_twitter_app
description: "supabase_twitter_app"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.5.2
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^14.2.3
  cached_network_image: ^3.4.1
  envied: ^0.5.4+1
  dio: ^5.6.0
  freezed_annotation: ^2.4.4
  flutter_hooks: ^0.20.5
  auto_translator: ^2.3.3
  pedantic_mono: ^1.27.0
  supabase_flutter: ^2.6.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  flutter_gen_runner:
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  envied_generator: ^0.5.4+1
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter_gen:
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  # fonts:
  #   - family: font_name
  #     fonts:
  #       - asset: fonts/font_file.ttf
